<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\ValidationException;

class UserRequest extends FormRequest {
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize() {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules() {
        return [
            'name' => 'required|min:2|max:50',
            'password' => 'required|min:2|max:50|confirmed',
            'email' => 'required|email|unique:users|max:50',
        ];
    }

    public function messages() {
      return [
          'name.required' => '用户名不能为空'
      ];
    }

    protected function failedValidation(Validator $validator) {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
